{{- if .Values.llmProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "presenton.fullname" . }}-llm-proxy"
  labels:
    {{- include "presenton.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-proxy
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "presenton.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: llm-proxy
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "presenton.labels" . | nindent 8 }}
        app.kubernetes.io/component: llm-proxy
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "presenton.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-llm-proxy"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.llmProxy.image.repository }}:{{ .Values.llmProxy.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.llmProxy.env.upstreamLlmUrl }}
          env:
            - name: UPSTREAM_LLM_URL
              value: {{ .Values.llmProxy.env.upstreamLlmUrl }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.llmProxy.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.llmProxy.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}   
      volumes:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}