apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma-db
  template:
    metadata:
      labels:
        app: chroma-db
        hpe-ezua/app: {{ .Chart.Name }}
        hpe-ezua/type: vendor-service
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: chromadb/chroma:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc
