apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-router
  namespace: {{ .Release.Namespace }}
  labels:
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "create", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "list"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-router
  namespace: {{ .Release.Namespace }}
  labels:
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-router
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-router
  namespace: {{ .Release.Namespace }}
