apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-auth-policy"
  namespace: istio-system
  labels:
    app: supabase-auth-policy
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - {{ .Values.ezua.virtualService.endpoint | required ".Values.ezua.virtualService.endpoint is required !\n" }}
            notPaths:
              - /auth/v1*
              - /rest/v1*
              - /graphql/v1*
              - /realtime/v1*
              - /storage/v1*
              - /functions/v1*
              - /pg*
              - /project/*
              - /studio/*
              - /mcp/*
              - /docs/*
  selector:
    matchLabels:
      istio: "ingressgateway"
