apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "milvus.fullname" . }}
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway | required ".Values.ezua.virtualService.istioGateway is required !\n" }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required ".Values.ezua.virtualService.endpoint is required !\n" }}
  http:
    - match:
      - uri:
          exact: /
      redirect:
        uri: /webui/
    - match:
      - uri:
          prefix: /webui
      route:
        - destination:
            # Insert target service name here
            host: {{ include "milvus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              # Insert target service port number here
              number: 9091