{{- if and .Values.recording.enabled (eq .Values.recording.volume.type "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediamtx.fullname" . }}-recordings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.recording.volume.size }}
  {{- with .Values.recording.volume.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
