{{- if .Values.minio.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secretName }}
  labels:
    {{- include "hpe-ezua.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | required "minio.accessKey is required when minio.createSecret=true" | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | required "minio.secretKey is required when minio.createSecret=true" | quote }}
{{- end }}
