{{- if .Values.kafkaUi.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kafka.fullname" . }}-ui
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway | required "ezua.virtualService.istioGateway is required" }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required "ezua.virtualService.endpoint is required" }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "kafka.fullname" . }}-ui.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
{{- end }}
