apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  selector:
    app: gitlab
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshPort }}
      protocol: TCP
