apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ printf "add-vendor-app-labels-%s-%s" .Release.Name .Chart.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  background: false
  rules:
  - name: add-vendor-app-labels
    match:
      any:
      - resources:
          # list all namespaces defined by the chart here
          # if there are no namespace resource defined leave only .Release.Namespace
          namespaces:
          - {{ .Release.Namespace }}
          kinds:
          - Pod
          - Deployment
          - Service
    mutate:
      patchStrategicMerge:
        metadata:
            labels:
              "hpe-ezua/type": vendor-service
              "hpe-ezua/app": {{ .Chart.Name }}
---

{{- if .Values.certificatesPolicy.enabled -}}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: >-
      Injects custom CA certificates into containers via volumes and env vars 
      when requested via annotations.
    policies.kyverno.io/minversion: 1.5.0
    policies.kyverno.io/title: Add Certificates as a Volume
    pod-policies.kyverno.io/autogen-controllers: none
  name: add-certificates-volume
spec:
  admission: true
  background: false
  rules:
  - name: add-ssl-certs
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: {{ print "{{ request.operation || 'BACKGROUND' }}" | quote }}
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    mutate:
      foreach:
      - list: request.object.spec.containers
        patchStrategicMerge:
          spec:
            containers:
            - name: {{ print "{{ element.name }}" | quote }}
              {{- if .Values.certificatesPolicy.env }}
              env:
                {{- toYaml .Values.certificatesPolicy.env | nindent 14 }}
              {{- end }}
              {{- if .Values.certificatesPolicy.volumeMounts }}
              volumeMounts:
                {{- toYaml .Values.certificatesPolicy.volumeMounts | nindent 14 }}
              {{- end }}
            {{- if .Values.certificatesPolicy.volumes }}
            volumes:
              {{- toYaml .Values.certificatesPolicy.volumes | nindent 12 }}
            {{- end }}
    skipBackgroundRequests: true
  validationFailureAction: Audit
{{- end -}}