apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pgvector.fullname" . }}
  namespace: {{ include "pgvector.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}